name: fanimation
description: Flutte animation example

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/launch_clouds.png
    - assets/images/launch_steam.png
    - assets/images/rocket.png

  
